/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AgeGroup = { 'teens' : null } |
  { 'kids' : null } |
  { 'adults' : null };
export type CourseLevel = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null };
export interface Lesson {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'level' : CourseLevel,
  'lessonType' : LessonType,
  'ageGroup' : AgeGroup,
}
export interface LessonCompletion {
  'lessonId' : bigint,
  'completedAt' : Time,
  'score' : bigint,
}
export type LessonType = { 'conversation' : null } |
  { 'grammar' : null } |
  { 'pronunciation' : null } |
  { 'vocabulary' : null };
export interface StreakTracking {
  'longestStreak' : bigint,
  'lastActive' : Time,
  'currentStreak' : bigint,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'courseLevel' : CourseLevel,
  'displayName' : string,
  'ageGroup' : AgeGroup,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createLesson' : ActorMethod<[Lesson], bigint>,
  'deleteLesson' : ActorMethod<[bigint], boolean>,
  'endChatSession' : ActorMethod<[bigint], boolean>,
  'getAllCourses' : ActorMethod<[], Array<Lesson>>,
  'getAllStreaks' : ActorMethod<[], Array<StreakTracking>>,
  'getAllStreaksByLongest' : ActorMethod<[], Array<StreakTracking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoursesByAgeLevel' : ActorMethod<[AgeGroup, CourseLevel], Array<Lesson>>,
  'getUserLessonCompletions' : ActorMethod<[], Array<LessonCompletion>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStreak' : ActorMethod<[], StreakTracking>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markLessonComplete' : ActorMethod<[bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessageToTutor' : ActorMethod<[bigint, string], string>,
  'startChatSession' : ActorMethod<[], bigint>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateLesson' : ActorMethod<[bigint, Lesson], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];