/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CourseLevel = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
});
export const LessonType = IDL.Variant({
  'conversation' : IDL.Null,
  'grammar' : IDL.Null,
  'pronunciation' : IDL.Null,
  'vocabulary' : IDL.Null,
});
export const AgeGroup = IDL.Variant({
  'teens' : IDL.Null,
  'kids' : IDL.Null,
  'adults' : IDL.Null,
});
export const Lesson = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'level' : CourseLevel,
  'lessonType' : LessonType,
  'ageGroup' : AgeGroup,
});
export const Time = IDL.Int;
export const StreakTracking = IDL.Record({
  'longestStreak' : IDL.Nat,
  'lastActive' : Time,
  'currentStreak' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'courseLevel' : CourseLevel,
  'displayName' : IDL.Text,
  'ageGroup' : AgeGroup,
});
export const LessonCompletion = IDL.Record({
  'lessonId' : IDL.Nat,
  'completedAt' : Time,
  'score' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createLesson' : IDL.Func([Lesson], [IDL.Nat], []),
  'deleteLesson' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'endChatSession' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
  'getAllStreaks' : IDL.Func([], [IDL.Vec(StreakTracking)], ['query']),
  'getAllStreaksByLongest' : IDL.Func([], [IDL.Vec(StreakTracking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoursesByAgeLevel' : IDL.Func(
      [AgeGroup, CourseLevel],
      [IDL.Vec(Lesson)],
      ['query'],
    ),
  'getUserLessonCompletions' : IDL.Func(
      [],
      [IDL.Vec(LessonCompletion)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStreak' : IDL.Func([], [StreakTracking], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markLessonComplete' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessageToTutor' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
  'startChatSession' : IDL.Func([], [IDL.Nat], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateLesson' : IDL.Func([IDL.Nat, Lesson], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CourseLevel = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  });
  const LessonType = IDL.Variant({
    'conversation' : IDL.Null,
    'grammar' : IDL.Null,
    'pronunciation' : IDL.Null,
    'vocabulary' : IDL.Null,
  });
  const AgeGroup = IDL.Variant({
    'teens' : IDL.Null,
    'kids' : IDL.Null,
    'adults' : IDL.Null,
  });
  const Lesson = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'level' : CourseLevel,
    'lessonType' : LessonType,
    'ageGroup' : AgeGroup,
  });
  const Time = IDL.Int;
  const StreakTracking = IDL.Record({
    'longestStreak' : IDL.Nat,
    'lastActive' : Time,
    'currentStreak' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'courseLevel' : CourseLevel,
    'displayName' : IDL.Text,
    'ageGroup' : AgeGroup,
  });
  const LessonCompletion = IDL.Record({
    'lessonId' : IDL.Nat,
    'completedAt' : Time,
    'score' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createLesson' : IDL.Func([Lesson], [IDL.Nat], []),
    'deleteLesson' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'endChatSession' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
    'getAllStreaks' : IDL.Func([], [IDL.Vec(StreakTracking)], ['query']),
    'getAllStreaksByLongest' : IDL.Func(
        [],
        [IDL.Vec(StreakTracking)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoursesByAgeLevel' : IDL.Func(
        [AgeGroup, CourseLevel],
        [IDL.Vec(Lesson)],
        ['query'],
      ),
    'getUserLessonCompletions' : IDL.Func(
        [],
        [IDL.Vec(LessonCompletion)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStreak' : IDL.Func([], [StreakTracking], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markLessonComplete' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessageToTutor' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
    'startChatSession' : IDL.Func([], [IDL.Nat], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateLesson' : IDL.Func([IDL.Nat, Lesson], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };