/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Lesson {
    id: bigint;
    title: string;
    description: string;
    level: CourseLevel;
    lessonType: LessonType;
    ageGroup: AgeGroup;
}
export interface StreakTracking {
    longestStreak: bigint;
    lastActive: Time;
    currentStreak: bigint;
}
export interface LessonCompletion {
    lessonId: bigint;
    completedAt: Time;
    score: bigint;
}
export interface UserProfile {
    courseLevel: CourseLevel;
    displayName: string;
    ageGroup: AgeGroup;
}
export interface http_header {
    value: string;
    name: string;
}
export enum AgeGroup {
    teens = "teens",
    kids = "kids",
    adults = "adults"
}
export enum CourseLevel {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced"
}
export enum LessonType {
    conversation = "conversation",
    grammar = "grammar",
    pronunciation = "pronunciation",
    vocabulary = "vocabulary"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface TeacherRecord {
    id: bigint;
    name: string;
    email: string;
    createdAt: bigint;
}
export interface StudentRecord {
    id: bigint;
    schoolName: string;
    studentName: string;
    mobileNumber: string;
    teacherId: bigint;
    createdAt: bigint;
}
export interface StudentProgress {
    currentModule: string;
    currentLesson: bigint;
    lastUpdated: bigint;
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createLesson(lesson: Lesson): Promise<bigint>;
    deleteLesson(lessonId: bigint): Promise<boolean>;
    endChatSession(sessionId: bigint): Promise<boolean>;
    getAllCourses(): Promise<Array<Lesson>>;
    getAllStreaks(): Promise<Array<StreakTracking>>;
    getAllStreaksByLongest(): Promise<Array<StreakTracking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCoursesByAgeLevel(ageGroup: AgeGroup, level: CourseLevel): Promise<Array<Lesson>>;
    getUserLessonCompletions(): Promise<Array<LessonCompletion>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserStreak(): Promise<StreakTracking>;
    isCallerAdmin(): Promise<boolean>;
    markLessonComplete(lessonId: bigint, score: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessageToTutor(sessionId: bigint, message: string): Promise<string>;
    startChatSession(): Promise<bigint>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateLesson(lessonId: bigint, lesson: Lesson): Promise<boolean>;
    createTeacher(name: string, email: string): Promise<bigint>;
    deleteTeacher(teacherId: bigint): Promise<boolean>;
    getAllTeachers(): Promise<Array<TeacherRecord>>;
    getTeacherById(teacherId: bigint): Promise<TeacherRecord | null>;
    createStudent(schoolName: string, studentName: string, mobileNumber: string, teacherId: bigint): Promise<bigint>;
    deleteStudent(studentId: bigint): Promise<boolean>;
    getStudentsByTeacher(teacherId: bigint): Promise<Array<StudentRecord>>;
    getAllStudents(): Promise<Array<StudentRecord>>;
    studentLogin(schoolName: string, studentName: string, mobileNumber: string): Promise<StudentRecord | null>;
    updateStudentProgress(studentId: bigint, currentModule: string, currentLesson: bigint): Promise<boolean>;
    getStudentProgress(studentId: bigint): Promise<StudentProgress | null>;
}
import type { AgeGroup as _AgeGroup, CourseLevel as _CourseLevel, Lesson as _Lesson, LessonType as _LessonType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createLesson(arg0: Lesson): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createLesson(to_candid_Lesson_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLesson(to_candid_Lesson_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteLesson(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLesson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLesson(arg0);
            return result;
        }
    }
    async endChatSession(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.endChatSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endChatSession(arg0);
            return result;
        }
    }
    async getAllCourses(): Promise<Array<Lesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCourses();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCourses();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStreaks(): Promise<Array<StreakTracking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStreaks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStreaks();
            return result;
        }
    }
    async getAllStreaksByLongest(): Promise<Array<StreakTracking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStreaksByLongest();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStreaksByLongest();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoursesByAgeLevel(arg0: AgeGroup, arg1: CourseLevel): Promise<Array<Lesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoursesByAgeLevel(to_candid_AgeGroup_n9(this._uploadFile, this._downloadFile, arg0), to_candid_CourseLevel_n5(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoursesByAgeLevel(to_candid_AgeGroup_n9(this._uploadFile, this._downloadFile, arg0), to_candid_CourseLevel_n5(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserLessonCompletions(): Promise<Array<LessonCompletion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserLessonCompletions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserLessonCompletions();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserStreak(): Promise<StreakTracking> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserStreak();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserStreak();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markLessonComplete(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markLessonComplete(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markLessonComplete(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessageToTutor(arg0: bigint, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessageToTutor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessageToTutor(arg0, arg1);
            return result;
        }
    }
    async startChatSession(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.startChatSession();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startChatSession();
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateLesson(arg0: bigint, arg1: Lesson): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLesson(arg0, to_candid_Lesson_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLesson(arg0, to_candid_Lesson_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createTeacher(name: string, email: string): Promise<bigint> {
        if (this.processError) {
            try {
                return await this.actor.createTeacher(name, email);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        }
        return await this.actor.createTeacher(name, email);
    }
    async deleteTeacher(teacherId: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                return await this.actor.deleteTeacher(teacherId);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        }
        return await this.actor.deleteTeacher(teacherId);
    }
    async getAllTeachers(): Promise<Array<TeacherRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeachers();
                return result.map(r => ({ id: r.id, name: r.name, email: r.email, createdAt: r.createdAt }));
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        }
        const result = await this.actor.getAllTeachers();
        return result.map(r => ({ id: r.id, name: r.name, email: r.email, createdAt: r.createdAt }));
    }
    async getTeacherById(teacherId: bigint): Promise<TeacherRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacherById(teacherId);
                return result.length === 0 ? null : { id: result[0].id, name: result[0].name, email: result[0].email, createdAt: result[0].createdAt };
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        }
        const result = await this.actor.getTeacherById(teacherId);
        return result.length === 0 ? null : { id: result[0].id, name: result[0].name, email: result[0].email, createdAt: result[0].createdAt };
    }
    async createStudent(schoolName: string, studentName: string, mobileNumber: string, teacherId: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                return await this.actor.createStudent(schoolName, studentName, mobileNumber, teacherId);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        }
        return await this.actor.createStudent(schoolName, studentName, mobileNumber, teacherId);
    }
    async deleteStudent(studentId: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                return await this.actor.deleteStudent(studentId);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        }
        return await this.actor.deleteStudent(studentId);
    }
    async getStudentsByTeacher(teacherId: bigint): Promise<Array<StudentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentsByTeacher(teacherId);
                return result.map(r => ({ id: r.id, schoolName: r.schoolName, studentName: r.studentName, mobileNumber: r.mobileNumber, teacherId: r.teacherId, createdAt: r.createdAt }));
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        }
        const result = await this.actor.getStudentsByTeacher(teacherId);
        return result.map(r => ({ id: r.id, schoolName: r.schoolName, studentName: r.studentName, mobileNumber: r.mobileNumber, teacherId: r.teacherId, createdAt: r.createdAt }));
    }
    async getAllStudents(): Promise<Array<StudentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return result.map(r => ({ id: r.id, schoolName: r.schoolName, studentName: r.studentName, mobileNumber: r.mobileNumber, teacherId: r.teacherId, createdAt: r.createdAt }));
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        }
        const result = await this.actor.getAllStudents();
        return result.map(r => ({ id: r.id, schoolName: r.schoolName, studentName: r.studentName, mobileNumber: r.mobileNumber, teacherId: r.teacherId, createdAt: r.createdAt }));
    }
    async studentLogin(schoolName: string, studentName: string, mobileNumber: string): Promise<StudentRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.studentLogin(schoolName, studentName, mobileNumber);
                return result.length === 0 ? null : { id: result[0].id, schoolName: result[0].schoolName, studentName: result[0].studentName, mobileNumber: result[0].mobileNumber, teacherId: result[0].teacherId, createdAt: result[0].createdAt };
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        }
        const result = await this.actor.studentLogin(schoolName, studentName, mobileNumber);
        return result.length === 0 ? null : { id: result[0].id, schoolName: result[0].schoolName, studentName: result[0].studentName, mobileNumber: result[0].mobileNumber, teacherId: result[0].teacherId, createdAt: result[0].createdAt };
    }
    async updateStudentProgress(studentId: bigint, currentModule: string, currentLesson: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                return await this.actor.updateStudentProgress(studentId, currentModule, currentLesson);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        }
        return await this.actor.updateStudentProgress(studentId, currentModule, currentLesson);
    }
    async getStudentProgress(studentId: bigint): Promise<StudentProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentProgress(studentId);
                return result.length === 0 ? null : { currentModule: result[0].currentModule, currentLesson: result[0].currentLesson, lastUpdated: result[0].lastUpdated };
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        }
        const result = await this.actor.getStudentProgress(studentId);
        return result.length === 0 ? null : { currentModule: result[0].currentModule, currentLesson: result[0].currentLesson, lastUpdated: result[0].lastUpdated };
    }
}
function from_candid_AgeGroup_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgeGroup): AgeGroup {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_CourseLevel_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CourseLevel): CourseLevel {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_LessonType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LessonType): LessonType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Lesson_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lesson): Lesson {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    description: string;
    level: _CourseLevel;
    lessonType: _LessonType;
    ageGroup: _AgeGroup;
}): {
    id: bigint;
    title: string;
    description: string;
    level: CourseLevel;
    lessonType: LessonType;
    ageGroup: AgeGroup;
} {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        level: from_candid_CourseLevel_n14(_uploadFile, _downloadFile, value.level),
        lessonType: from_candid_LessonType_n16(_uploadFile, _downloadFile, value.lessonType),
        ageGroup: from_candid_AgeGroup_n18(_uploadFile, _downloadFile, value.ageGroup)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    courseLevel: _CourseLevel;
    displayName: string;
    ageGroup: _AgeGroup;
}): {
    courseLevel: CourseLevel;
    displayName: string;
    ageGroup: AgeGroup;
} {
    return {
        courseLevel: from_candid_CourseLevel_n14(_uploadFile, _downloadFile, value.courseLevel),
        displayName: value.displayName,
        ageGroup: from_candid_AgeGroup_n18(_uploadFile, _downloadFile, value.ageGroup)
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
}): CourseLevel {
    return "intermediate" in value ? CourseLevel.intermediate : "beginner" in value ? CourseLevel.beginner : "advanced" in value ? CourseLevel.advanced : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    conversation: null;
} | {
    grammar: null;
} | {
    pronunciation: null;
} | {
    vocabulary: null;
}): LessonType {
    return "conversation" in value ? LessonType.conversation : "grammar" in value ? LessonType.grammar : "pronunciation" in value ? LessonType.pronunciation : "vocabulary" in value ? LessonType.vocabulary : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    teens: null;
} | {
    kids: null;
} | {
    adults: null;
}): AgeGroup {
    return "teens" in value ? AgeGroup.teens : "kids" in value ? AgeGroup.kids : "adults" in value ? AgeGroup.adults : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lesson>): Array<Lesson> {
    return value.map((x)=>from_candid_Lesson_n12(_uploadFile, _downloadFile, x));
}
function to_candid_AgeGroup_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgeGroup): _AgeGroup {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_CourseLevel_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CourseLevel): _CourseLevel {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_LessonType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LessonType): _LessonType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Lesson_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Lesson): _Lesson {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    courseLevel: CourseLevel;
    displayName: string;
    ageGroup: AgeGroup;
}): {
    courseLevel: _CourseLevel;
    displayName: string;
    ageGroup: _AgeGroup;
} {
    return {
        courseLevel: to_candid_CourseLevel_n5(_uploadFile, _downloadFile, value.courseLevel),
        displayName: value.displayName,
        ageGroup: to_candid_AgeGroup_n9(_uploadFile, _downloadFile, value.ageGroup)
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    description: string;
    level: CourseLevel;
    lessonType: LessonType;
    ageGroup: AgeGroup;
}): {
    id: bigint;
    title: string;
    description: string;
    level: _CourseLevel;
    lessonType: _LessonType;
    ageGroup: _AgeGroup;
} {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        level: to_candid_CourseLevel_n5(_uploadFile, _downloadFile, value.level),
        lessonType: to_candid_LessonType_n7(_uploadFile, _downloadFile, value.lessonType),
        ageGroup: to_candid_AgeGroup_n9(_uploadFile, _downloadFile, value.ageGroup)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgeGroup): {
    teens: null;
} | {
    kids: null;
} | {
    adults: null;
} {
    return value == AgeGroup.teens ? {
        teens: null
    } : value == AgeGroup.kids ? {
        kids: null
    } : value == AgeGroup.adults ? {
        adults: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CourseLevel): {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} {
    return value == CourseLevel.intermediate ? {
        intermediate: null
    } : value == CourseLevel.beginner ? {
        beginner: null
    } : value == CourseLevel.advanced ? {
        advanced: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LessonType): {
    conversation: null;
} | {
    grammar: null;
} | {
    pronunciation: null;
} | {
    vocabulary: null;
} {
    return value == LessonType.conversation ? {
        conversation: null
    } : value == LessonType.grammar ? {
        grammar: null
    } : value == LessonType.pronunciation ? {
        pronunciation: null
    } : value == LessonType.vocabulary ? {
        vocabulary: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
